#!/bin/sh

#
# Start script for the UDT-Java send-file application
# Usage: receive-file <server-address> <server-port> <remote-file> <local-file>
#                     [--localIP=<local ip>]
#                     [--localPort=<local port>] 
#                     [--verbose]
#
#

#
#Installation Directory
#
dir=`dirname $0`
if [ "$dir" != "." ]
then
  INST=`dirname $dir`
else
  pwd | grep -e 'bin$' > /dev/null
  if [ $? = 0 ]
  then
    INST=".."
  else
    INST=`dirname $dir`
  fi
fi

INST=${INST:-.}

#
#Alternatively specify the installation dir here
#
#INST=

#
# Alternative CC class
#
#OPTS=$OPTS" -Dudt.congestioncontrol.class=udt.cc.SimpleTCP"

#Java command to use
JAVA=java

#location of udt.jar
CP=$INST/lib/udt*.jar

#memory for the VM
MEM=-Xmx128m

$JAVA $MEM $OPTS -cp $CP udt.util.ReceiveFile $*

